# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0003_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('Jan', models.CharField(max_length=30)),
                ('Feb', models.CharField(max_length=30)),
                ('Mar', models.CharField(max_length=30)),
                ('Apr', models.CharField(max_length=30)),
                ('Jun', models.CharField(max_length=30)),
                ('Jul', models.CharField(max_length=30)),
                ('Aug', models.CharField(max_length=30)),
                ('Sep', models.CharField(max_length=30)),
                ('Oct', models.CharField(max_length=30)),
                ('Nov', models.CharField(max_length=30)),
                ('Dec', models.CharField(max_length=30)),
            ],
        ),
    ]
