# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0006_dashboard_daily_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_daily_sales',
            name='date',
        ),
        migrations.AddField(
            model_name='dashboard_daily_sales',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
