# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0008_auto_20171127_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='eighteen_to_twenty',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='fourteen_to_sixteen',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='sixteen_to_eighteen',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='ten_to_twelve',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='twelve_to_fourteen',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dashboard_daily_sales',
            name='twenty_to_twentytwo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
