# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0010_auto_20171129_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmonthly',
            name='year',
            field=models.TextField(max_length=30),
        ),
    ]
