# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0011_auto_20171129_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmonthly',
            old_name='year',
            new_name='Year',
        ),
    ]
