# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodML', '0012_auto_20171129_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='admin', max_length=16),
            preserve_default=False,
        ),
    ]
